server:
  port: 8088

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/MicroService_Booking
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    import: optional:configserver:http://localhost:8085

management:
    endpoints:
      web:
        exposure:
          include: health, info, prometheus


resilience4j:
  circuitbreaker:
    instances:
      hotelServiceBreaker:
        registerHealthIndicator: true
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowType: COUNT_BASED
        minimumNumberOfCalls: 5
        waitDurationInOpenState: 30s
        failureRateThreshold: 50
  retry:
    instances:
      hotelServiceRetry:
        maxAttempts: 3
        waitDuration: 2s