server:
  port: 8088

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/MicroService_Booking
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    import: optional:configserver:http://localhost:8085

    #Kafka


  kafka:
      # Kafka broker address
    bootstrap-servers: localhost:9092

      # Producer Configuration
    producer:
        # Serializer for message keys
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        # Serializer for message values
        value-serializer: org.apache.kafka.common.serialization.StringSerializer
        # Acknowledgment mode (all = wait for all replicas)
        acks: all
        # Number of retries on failure
        retries: 3
        # Enable idempotence (prevent duplicate messages)
        properties:
          enable.idempotence: true
          # Request timeout
          request.timeout.ms: 30000
          # Delivery timeout
          delivery.timeout.ms: 120000
          # Compression type (none, gzip, snappy, lz4, zstd)
          compression.type: lz4
          # Batch size in bytes
          batch.size: 16384
          # Linger time in ms (wait to batch messages)
          linger.ms: 5
          # Buffer memory
          buffer.memory: 33554432

      # Consumer Configuration (for later use)
    consumer:
        group-id: user-service-group
        auto-offset-reset: earliest
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        properties:
          spring.json.trusted.packages: "*"





management:
    endpoints:
      web:
        exposure:
          include: health, info, prometheus


resilience4j:
  circuitbreaker:
    instances:
      hotelServiceBreaker:
        registerHealthIndicator: true
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowType: COUNT_BASED
        minimumNumberOfCalls: 5
        waitDurationInOpenState: 30s
        failureRateThreshold: 50
  retry:
    instances:
      hotelServiceRetry:
        maxAttempts: 3
        waitDuration: 2s